In [2]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing
import matplotlib.pyplot as plt 
import seaborn as sns
import math
from scipy.stats import shapiro 
from scipy.stats import lognorm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler

In [3]:
train = pd.read_csv('data_source/train.csv')
test = pd.read_csv('data_source/test.csv')

X_train = train.loc[:,['Source Port', 'Destination Port', 'NAT Source Port', 'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received', 'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received']]
y_train = train.loc[:,'Action']
X_test = test.loc[:,['Source Port', 'Destination Port', 'NAT Source Port', 'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received', 'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received']]
y_test = test.loc[:,'Action']

In [5]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [6]:
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.997914547304171


In [7]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[11290     2     0     0]
 [    1  4484    10     1]
 [    0    16  3840     0]
 [    0    11     0     5]]
              precision    recall  f1-score   support

       allow       1.00      1.00      1.00     11292
        deny       0.99      1.00      1.00      4496
        drop       1.00      1.00      1.00      3856
  reset-both       0.83      0.31      0.45        16

    accuracy                           1.00     19660
   macro avg       0.96      0.83      0.86     19660
weighted avg       1.00      1.00      1.00     19660



In [12]:
!pip install pip install pydotplus
from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus
from sklearn.metrics import classification_report, confusion_matrix  

In [9]:
from sklearn.tree import export_graphviz

In [ ]:
export_graphviz(tree_in_forest,
                feature_names=X.columns,
                filled=True,
                rounded=True)

In [33]:
scaler = StandardScaler()
X_train.loc[:,['Packets','Elapsed Time (sec)','Bytes Received']] = scaler.fit_transform(X_train.loc[:,['Packets','Elapsed Time (sec)','Bytes Received']])
X_test.loc[:,['Packets','Elapsed Time (sec)','Bytes Received']] = scaler.fit_transform(X_test.loc[:,['Packets','Elapsed Time (sec)','Bytes Received']])

y_train.replace({'allow':0, 'deny':1, 'drop':2, 'reset-both':3},inplace=True)
y_test.replace({'allow':0, 'deny':1, 'drop':2, 'reset-both':3},inplace=True)

In [34]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.996439471007121


In [36]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[11243    49     0     0]
 [    2  4481    11     2]
 [    0     0  3856     0]
 [    0     6     0    10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     11292
           1       0.99      1.00      0.99      4496
           2       1.00      1.00      1.00      3856
           3       0.83      0.62      0.71        16

    accuracy                           1.00     19660
   macro avg       0.95      0.90      0.93     19660
weighted avg       1.00      1.00      1.00     19660

